{% set version = "2.1.3" %}

package:
  name: nteract_on_jupyter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nteract_on_jupyter/nteract_on_jupyter-{{ version }}.tar.gz
  sha256: 3cb096237aeecb60c54e2428d21e08de30cde2d87f1d3890725d1d7991dd8056

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - jupyter-nteract = nteract_on_jupyter.nteractapp:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - notebook

test:
  requires:
    - python {{ python_min }}
  imports:
    - nteract_on_jupyter
  commands:
    - jupyter-nteract --help

about:
  home: https://github.com/nteract/nteract
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extension for the jupyter notebook server and nteract

extra:
  recipe-maintainers:
    - ocefpaf
